// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionTracker.SqlServer.Data;

#nullable disable

namespace NutritionTracker.SqlServer.Migrations
{
    [DbContext(typeof(NutritionTrackerDbContext))]
    partial class NutritionTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.FoodItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("FoodLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FoodLogId");

                    b.Property<Guid>("FoodNutritionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FoodNutritionId");

                    b.Property<int>("Unit")
                        .HasColumnType("int")
                        .HasColumnName("Unit");

                    b.HasKey("Id");

                    b.HasIndex("FoodLogId");

                    b.HasIndex("FoodNutritionId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.FoodLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CreateTime");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("DateTime");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("float")
                        .HasColumnName("TotalCalories");

                    b.Property<double>("TotalCarbs")
                        .HasColumnType("float")
                        .HasColumnName("TotalCarbs");

                    b.Property<double>("TotalFat")
                        .HasColumnType("float")
                        .HasColumnName("TotalFat");

                    b.Property<double>("TotalProtein")
                        .HasColumnType("float")
                        .HasColumnName("TotalProtein");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdateTime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodLogs");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.FoodNutritionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<double>("Calories")
                        .HasColumnType("float")
                        .HasColumnName("Calories");

                    b.Property<double>("Carbs")
                        .HasColumnType("float")
                        .HasColumnName("Carbs");

                    b.Property<double>("Fat")
                        .HasColumnType("float")
                        .HasColumnName("Fat");

                    b.Property<string>("Measurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Measurement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<double>("Protein")
                        .HasColumnType("float")
                        .HasColumnName("Protein");

                    b.HasKey("Id");

                    b.ToTable("FoodNutritions");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<double>("SuggestedCalories")
                        .HasColumnType("float")
                        .HasColumnName("SuggestedCalories");

                    b.Property<double>("SuggestedCarbs")
                        .HasColumnType("float")
                        .HasColumnName("SuggestedCarbs");

                    b.Property<double>("SuggestedFat")
                        .HasColumnType("float")
                        .HasColumnName("SuggestedFat");

                    b.Property<double>("SuggestedProtein")
                        .HasColumnType("float")
                        .HasColumnName("SuggestedProtein");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.FoodItemEntity", b =>
                {
                    b.HasOne("NutritionTracker.SqlServer.Entities.FoodLogEntity", "FoodLog")
                        .WithMany("FoodItems")
                        .HasForeignKey("FoodLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionTracker.SqlServer.Entities.FoodNutritionEntity", "FoodNutrition")
                        .WithMany("FoodItems")
                        .HasForeignKey("FoodNutritionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoodLog");

                    b.Navigation("FoodNutrition");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.FoodLogEntity", b =>
                {
                    b.HasOne("NutritionTracker.SqlServer.Entities.UserEntity", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.FoodLogEntity", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.FoodNutritionEntity", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("NutritionTracker.SqlServer.Entities.UserEntity", b =>
                {
                    b.Navigation("FoodLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
