# Azure DevOps Pipeline - Deploy Application
# Path: deployment/pipelines/azure-devops-deploy.yml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/Adapters/Input/NutritionTracker.AzureFunctions/**
      - src/Adapters/Output/NutritionTracker.AzureTableStorage/**
      - src/Core/**

parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'dev'
  values:
  - dev
  - staging
  - production

variables:
  functionAppName: 'func-nutrition-tracker-${{ parameters.environment }}'
  resourceGroup: 'rg-nutrition-tracker-${{ parameters.environment }}'
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build and Publish'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        version: $(dotnetVersion)
        packageType: sdk

    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: 'restore'
        projects: 'src/NutritionTracker.sln'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: 'src/NutritionTracker.sln'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: 'src/NutritionTracker.sln'
        arguments: '--configuration $(buildConfiguration) --no-build'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Azure Functions'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'src/Adapters/Input/NutritionTracker.AzureFunctions/NutritionTracker.AzureFunctions.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'function-app'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployFunctionApp
    displayName: 'Deploy Function App'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'function-app'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureFunctionApp@2
            displayName: 'Deploy Azure Function'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'functionAppLinux'
              appName: '$(functionAppName)'
              package: '$(System.ArtifactsDirectory)/function-app/**/*.zip'
              runtimeStack: 'DOTNET-ISOLATED|8.0'

          - task: AzureCLI@2
            displayName: 'Validate deployment'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                FUNCTION_URL=$(az functionapp show \
                  --name $(functionAppName) \
                  --resource-group $(resourceGroup) \
                  --query defaultHostName -o tsv)
                
                echo "Function App deployed successfully!"
                echo "URL: https://$FUNCTION_URL"
                echo "Testing endpoint..."
                
                curl -s "https://$FUNCTION_URL/api/users" || echo "Endpoint not ready yet (may take a few minutes)"
